#!/usr/bin/env bash

VERSION=$1

if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid version number. Please use the format x.y.z"
  exit 1
fi

TAG_NAME="v$VERSION"

git tag "$TAG_NAME"
git push origin "$TAG_NAME"
