name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  PLUGIN_ID: shrinkwrap

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch main
        run: git fetch origin main

      - name: Exit if tagged commit has not been committed to main
        run: |
          if [[ ! $(git tag --merged "origin/main") =~ "${{ github.ref_name }}" ]]; then
            echo "Tagged commit has not been merged to main (tag: '${{ github.ref_name }}')"
            exit -1
          fi

      - name: Exit if tag does not match plugin version
        run: |
          tag_name=${{ github.ref_name }}
          plugin_version=$(grep -oP --color=never "(?<=^version=)v[\d\.]+$" gradle.properties)
          if [[ ! $tag_name = $plugin_version ]]; then
            echo "Tag does not match plugin version (tag: '$tag_name', plugin version: '$plugin_version')"
            exit -1
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build plugin to distribution JAR
        run: ./gradlew build

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{  github.ref_name }}"
          release_name: ${{  github.ref_name }}"
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/dist/${{ env.PLUGIN_ID }}.jar
          asset_name: ${{ env.PLUGIN_ID }}.jar
          asset_content_type: application/java-archive

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
